name: Validate Breaking Change PR
description: Validate breaking change PR title and description

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: npx tsx ../../../packages/repo-tools/src/breaking-pr-action-check.mts
