name: Validate Breaking Change PR
description: Validate breaking change PR title and description

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: cd ../../../packages/repo-tools && yarn breaking-pr-check-action
