name: Validate Breaking Change PR
description: Validate breaking change PR title and description

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: yarn breaking-pr-check-action
      working-directory: packages/repo-tools
